### ISSUE TITLE
Travis CI build is failing

### ISSUE THREAD

**Issue by yous** [aheui/naheui#6]
See https://travis-ci.org/aheui/naheui/builds/72676825.

Actually this problem occurred by https://github.com/aheui/snippets/commit/1de473c1475f4d4abe073783e0d4d00585c16b27, as `"../cli.js --interactive-message=false"` has being treated as a name of single file.

**Comment by disjukr** [comment]
fixed test script. but bieup test is failing.
maybe because of https://twitter.com/x_nuk/status/625326778005860353

**Comment by disjukr** [comment]
fixed by https://github.com/aheui/naheui/pull/7
