### ISSUE TITLE
(node) util.print is deprecated. Use console.log instead.

### ISSUE THREAD

**Issue by sungwoncho** [aheui/naheui#8]
**Version**

* node: 4.3.1
* naheui: 0.3.1

**Reproduction**

1. Run hello world example.
2. It gives `(node) util.print is deprecated. Use console.log instead.` 

Happy to make PR.

**Comment by disjukr** [comment]
[already fixed](https://github.com/aheui/naheui/commit/4a3a0a5127a341a1907690a6dc6fb11393dcc969) but it seems not released yet. i'll see this on weekend
